const appName = "eMart";
const appVersion = "Version 1.0.0";
const credits = "@Khubaib Jamal";
const name = "Name";
const nameHint = "John";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "********";
const confirmPassword = "Confirm Password";
const confirmPasswordHint = "********";
const forgetPassword = "Forget Password";
const login = "Login";
const signUp = "Sign-up";
const createNewAccount = "Create New Account";
const privacyPolicy = "Privacy Policy";
const termAndCondition = "Term and Condition";
const alreadyHaveAnAccount = "Already Have An Account";
const loginWith = "Login With";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
